```{r, child = "refactor-dry-ex.Rmd"}
```

----------------------------------------------------

### Lösung:

```{r eval = FALSE}
# always set a seed for reproducibility
set.seed(141516)

x <- rnorm(100)
y <- rnorm(100)
z <- rnorm(100)
v <- z^2

# simple result of <Ctrl+Alt+X> on the relevant lines:
compute_ci <- function(x) {
  m <- mean(x)
  s <- sd(x)
  n <- length(x)
  c(m - 1.96 * s / sqrt(n), m + 1.96 * s / sqrt(n))
}

compute_ci(x)
compute_ci(y)
compute_ci(z)
compute_ci(v)
```
Aaaah. So! viel! schöööner! 


Wenn wir was wirklich weiter wiederverwenden wollen würden, wären wir wohl weiser wenn wir wohlweislich wie wahre Wissenschaftler werkeln würden:
```{r}
# overkill: fancy version 
#  - argument checks
#  - 95% level of CI not hard-coded, but set as default
#  - descriptive variable names
#  - deal with NAs
compute_ci <- function(x, level = 0.95) {
  checkmate::assert_numeric(x)
  n_valid <- length(x) - sum(is.na(x))
  if (n_valid < 2) {
    warning("not enough non-missing values in ", deparse(substitute(x)), 
         " to compute CI")
    return(c(NA_real_, NA_real_))
  }
  checkmate::assert_number(level, lower = 0, upper = 1)
  width_factor <- abs(qnorm((1 - level) / 2))
  half_width <- width_factor * sd(x, na.rm = TRUE) / sqrt(n_valid)
  mean(x, na.rm = TRUE) + c(-half_width, half_width)
}
```
